[package]
name = "nbt"
version = "0.1.0"
edition = "2021"

[lib]
name = "nbt"
path = "src/lib.rs"

[dependencies]
byteorder = "1.4.3"
flate2 = "1.0.28"
paste = "1.0.14"
serde = { version="1.0.193", features = ["derive"] }

[features]
debug = []